#pragma once
// Generated by scripts/gen_theme_fields.py from BaseTheme.h - DO NOT EDIT.
// Stable field-id registry for .uipack theme overrides (docs/live-studio-v1.md).
// Ids are declaration order and must never be reordered or reused.

#include <cstdint>

#include "components/themes/BaseTheme.h"

namespace PocketDaily::LiveStudio::ThemeField {

enum FieldId : uint16_t {
  kBatteryWidth = 0,
  kBatteryHeight = 1,
  kTopPadding = 2,
  kBatteryBarHeight = 3,
  kHeaderHeight = 4,
  kVerticalSpacing = 5,
  kPreviewPadding = 6,
  kPreviewHeightPercent = 7,
  kContentSidePadding = 8,
  kListRowHeight = 9,
  kListWithSubtitleRowHeight = 10,
  kMenuRowHeight = 11,
  kMenuSpacing = 12,
  kTabSpacing = 13,
  kTabBarHeight = 14,
  kScrollBarWidth = 15,
  kScrollBarRightOffset = 16,
  kHomeTopPadding = 17,
  kHomeCoverHeight = 18,
  kHomeCoverTileHeight = 19,
  kHomeRecentBooksCount = 20,
  kHomeContinueReadingInMenu = 21,
  kHomeMenuTopOffset = 22,
  kButtonHintsHeight = 23,
  kSideButtonHintsWidth = 24,
  kProgressBarHeight = 25,
  kProgressBarMarginTop = 26,
  kStatusBarHorizontalMargin = 27,
  kStatusBarVerticalMargin = 28,
  kKeyboardKeyWidth = 29,
  kKeyboardKeyHeight = 30,
  kKeyboardKeySpacing = 31,
  kKeyboardBottomKeyHeight = 32,
  kKeyboardBottomKeySpacing = 33,
  kKeyboardBottomAligned = 34,
  kKeyboardCenteredText = 35,
  kKeyboardVerticalOffset = 36,
  kKeyboardTextFieldWidthPercent = 37,
  kKeyboardWidthPercent = 38,
  kKeyboardKeyCornerRadius = 39,
  kKeyboardFillUnselected = 40,
  kKeyboardOutlineAllUnselected = 41,
  kKeyboardDrawSpecialOutlineWhenUnselected = 42,
  kKeyboardSecondaryLabelRightPadding = 43,
  kKeyboardSecondaryLabelTopPadding = 44,
  kKeyboardMinArrowHeadSize = 45,
  kPopupTopOffsetRatio = 46,
  kPopupMarginX = 47,
  kPopupMarginY = 48,
  kPopupFrameThickness = 49,
  kPopupCornerRadius = 50,
  kPopupTextBold = 51,
  kPopupTextInverted = 52,
  kPopupTextBaselineOffsetY = 53,
  kPopupProgressBarHeight = 54,
  kPopupProgressDrawOutline = 55,
  kPopupProgressClampPercent = 56,
  kPopupProgressFillInverted = 57,
  kPopupProgressOutlineInverted = 58,
  kTextFieldHorizontalPadding = 59,
  kTextFieldNormalThickness = 60,
  kTextFieldCursorThickness = 61,
  kTextFieldLineEndOffset = 62
};

inline constexpr size_t kFieldCount = 63;

// 1=int, 2=bool, 3=float - the .uipack record type codes.
struct FieldDef {
  const char* name;
  uint8_t type;
  uint16_t offset;
};

inline constexpr FieldDef kFields[kFieldCount] = {
    {"batteryWidth", 1, __builtin_offsetof(ThemeMetrics, batteryWidth)},
    {"batteryHeight", 1, __builtin_offsetof(ThemeMetrics, batteryHeight)},
    {"topPadding", 1, __builtin_offsetof(ThemeMetrics, topPadding)},
    {"batteryBarHeight", 1, __builtin_offsetof(ThemeMetrics, batteryBarHeight)},
    {"headerHeight", 1, __builtin_offsetof(ThemeMetrics, headerHeight)},
    {"verticalSpacing", 1, __builtin_offsetof(ThemeMetrics, verticalSpacing)},
    {"previewPadding", 1, __builtin_offsetof(ThemeMetrics, previewPadding)},
    {"previewHeightPercent", 1, __builtin_offsetof(ThemeMetrics, previewHeightPercent)},
    {"contentSidePadding", 1, __builtin_offsetof(ThemeMetrics, contentSidePadding)},
    {"listRowHeight", 1, __builtin_offsetof(ThemeMetrics, listRowHeight)},
    {"listWithSubtitleRowHeight", 1, __builtin_offsetof(ThemeMetrics, listWithSubtitleRowHeight)},
    {"menuRowHeight", 1, __builtin_offsetof(ThemeMetrics, menuRowHeight)},
    {"menuSpacing", 1, __builtin_offsetof(ThemeMetrics, menuSpacing)},
    {"tabSpacing", 1, __builtin_offsetof(ThemeMetrics, tabSpacing)},
    {"tabBarHeight", 1, __builtin_offsetof(ThemeMetrics, tabBarHeight)},
    {"scrollBarWidth", 1, __builtin_offsetof(ThemeMetrics, scrollBarWidth)},
    {"scrollBarRightOffset", 1, __builtin_offsetof(ThemeMetrics, scrollBarRightOffset)},
    {"homeTopPadding", 1, __builtin_offsetof(ThemeMetrics, homeTopPadding)},
    {"homeCoverHeight", 1, __builtin_offsetof(ThemeMetrics, homeCoverHeight)},
    {"homeCoverTileHeight", 1, __builtin_offsetof(ThemeMetrics, homeCoverTileHeight)},
    {"homeRecentBooksCount", 1, __builtin_offsetof(ThemeMetrics, homeRecentBooksCount)},
    {"homeContinueReadingInMenu", 2, __builtin_offsetof(ThemeMetrics, homeContinueReadingInMenu)},
    {"homeMenuTopOffset", 1, __builtin_offsetof(ThemeMetrics, homeMenuTopOffset)},
    {"buttonHintsHeight", 1, __builtin_offsetof(ThemeMetrics, buttonHintsHeight)},
    {"sideButtonHintsWidth", 1, __builtin_offsetof(ThemeMetrics, sideButtonHintsWidth)},
    {"progressBarHeight", 1, __builtin_offsetof(ThemeMetrics, progressBarHeight)},
    {"progressBarMarginTop", 1, __builtin_offsetof(ThemeMetrics, progressBarMarginTop)},
    {"statusBarHorizontalMargin", 1, __builtin_offsetof(ThemeMetrics, statusBarHorizontalMargin)},
    {"statusBarVerticalMargin", 1, __builtin_offsetof(ThemeMetrics, statusBarVerticalMargin)},
    {"keyboardKeyWidth", 1, __builtin_offsetof(ThemeMetrics, keyboardKeyWidth)},
    {"keyboardKeyHeight", 1, __builtin_offsetof(ThemeMetrics, keyboardKeyHeight)},
    {"keyboardKeySpacing", 1, __builtin_offsetof(ThemeMetrics, keyboardKeySpacing)},
    {"keyboardBottomKeyHeight", 1, __builtin_offsetof(ThemeMetrics, keyboardBottomKeyHeight)},
    {"keyboardBottomKeySpacing", 1, __builtin_offsetof(ThemeMetrics, keyboardBottomKeySpacing)},
    {"keyboardBottomAligned", 2, __builtin_offsetof(ThemeMetrics, keyboardBottomAligned)},
    {"keyboardCenteredText", 2, __builtin_offsetof(ThemeMetrics, keyboardCenteredText)},
    {"keyboardVerticalOffset", 1, __builtin_offsetof(ThemeMetrics, keyboardVerticalOffset)},
    {"keyboardTextFieldWidthPercent", 1, __builtin_offsetof(ThemeMetrics, keyboardTextFieldWidthPercent)},
    {"keyboardWidthPercent", 1, __builtin_offsetof(ThemeMetrics, keyboardWidthPercent)},
    {"keyboardKeyCornerRadius", 1, __builtin_offsetof(ThemeMetrics, keyboardKeyCornerRadius)},
    {"keyboardFillUnselected", 2, __builtin_offsetof(ThemeMetrics, keyboardFillUnselected)},
    {"keyboardOutlineAllUnselected", 2, __builtin_offsetof(ThemeMetrics, keyboardOutlineAllUnselected)},
    {"keyboardDrawSpecialOutlineWhenUnselected", 2,
     __builtin_offsetof(ThemeMetrics, keyboardDrawSpecialOutlineWhenUnselected)},
    {"keyboardSecondaryLabelRightPadding", 1, __builtin_offsetof(ThemeMetrics, keyboardSecondaryLabelRightPadding)},
    {"keyboardSecondaryLabelTopPadding", 1, __builtin_offsetof(ThemeMetrics, keyboardSecondaryLabelTopPadding)},
    {"keyboardMinArrowHeadSize", 1, __builtin_offsetof(ThemeMetrics, keyboardMinArrowHeadSize)},
    {"popupTopOffsetRatio", 3, __builtin_offsetof(ThemeMetrics, popupTopOffsetRatio)},
    {"popupMarginX", 1, __builtin_offsetof(ThemeMetrics, popupMarginX)},
    {"popupMarginY", 1, __builtin_offsetof(ThemeMetrics, popupMarginY)},
    {"popupFrameThickness", 1, __builtin_offsetof(ThemeMetrics, popupFrameThickness)},
    {"popupCornerRadius", 1, __builtin_offsetof(ThemeMetrics, popupCornerRadius)},
    {"popupTextBold", 2, __builtin_offsetof(ThemeMetrics, popupTextBold)},
    {"popupTextInverted", 2, __builtin_offsetof(ThemeMetrics, popupTextInverted)},
    {"popupTextBaselineOffsetY", 1, __builtin_offsetof(ThemeMetrics, popupTextBaselineOffsetY)},
    {"popupProgressBarHeight", 1, __builtin_offsetof(ThemeMetrics, popupProgressBarHeight)},
    {"popupProgressDrawOutline", 2, __builtin_offsetof(ThemeMetrics, popupProgressDrawOutline)},
    {"popupProgressClampPercent", 2, __builtin_offsetof(ThemeMetrics, popupProgressClampPercent)},
    {"popupProgressFillInverted", 2, __builtin_offsetof(ThemeMetrics, popupProgressFillInverted)},
    {"popupProgressOutlineInverted", 2, __builtin_offsetof(ThemeMetrics, popupProgressOutlineInverted)},
    {"textFieldHorizontalPadding", 1, __builtin_offsetof(ThemeMetrics, textFieldHorizontalPadding)},
    {"textFieldNormalThickness", 1, __builtin_offsetof(ThemeMetrics, textFieldNormalThickness)},
    {"textFieldCursorThickness", 1, __builtin_offsetof(ThemeMetrics, textFieldCursorThickness)},
    {"textFieldLineEndOffset", 1, __builtin_offsetof(ThemeMetrics, textFieldLineEndOffset)},
};

// Applies one validated override. Unknown ids are ignored by the caller's
// whitelist check; this switch is the single write path.
inline void applyOverride(ThemeMetrics& metrics, uint16_t id, uint8_t type, int32_t value) {
  if (id >= kFieldCount || type != kFields[id].type) return;
  switch (id) {
    case 0:
      *reinterpret_cast<decltype(metrics.batteryWidth)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[0].offset) =
          value;
      break;
    case 1:
      *reinterpret_cast<decltype(metrics.batteryHeight)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[1].offset) =
          value;
      break;
    case 2:
      *reinterpret_cast<decltype(metrics.topPadding)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[2].offset) =
          value;
      break;
    case 3:
      *reinterpret_cast<decltype(metrics.batteryBarHeight)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[3].offset) =
          value;
      break;
    case 4:
      *reinterpret_cast<decltype(metrics.headerHeight)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[4].offset) =
          value;
      break;
    case 5:
      *reinterpret_cast<decltype(metrics.verticalSpacing)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[5].offset) =
          value;
      break;
    case 6:
      *reinterpret_cast<decltype(metrics.previewPadding)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[6].offset) =
          value;
      break;
    case 7:
      *reinterpret_cast<decltype(metrics.previewHeightPercent)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                 kFields[7].offset) = value;
      break;
    case 8:
      *reinterpret_cast<decltype(metrics.contentSidePadding)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                               kFields[8].offset) = value;
      break;
    case 9:
      *reinterpret_cast<decltype(metrics.listRowHeight)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[9].offset) =
          value;
      break;
    case 10:
      *reinterpret_cast<decltype(metrics.listWithSubtitleRowHeight)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                      kFields[10].offset) = value;
      break;
    case 11:
      *reinterpret_cast<decltype(metrics.menuRowHeight)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[11].offset) =
          value;
      break;
    case 12:
      *reinterpret_cast<decltype(metrics.menuSpacing)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[12].offset) =
          value;
      break;
    case 13:
      *reinterpret_cast<decltype(metrics.tabSpacing)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[13].offset) =
          value;
      break;
    case 14:
      *reinterpret_cast<decltype(metrics.tabBarHeight)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[14].offset) =
          value;
      break;
    case 15:
      *reinterpret_cast<decltype(metrics.scrollBarWidth)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[15].offset) =
          value;
      break;
    case 16:
      *reinterpret_cast<decltype(metrics.scrollBarRightOffset)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                 kFields[16].offset) = value;
      break;
    case 17:
      *reinterpret_cast<decltype(metrics.homeTopPadding)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[17].offset) =
          value;
      break;
    case 18:
      *reinterpret_cast<decltype(metrics.homeCoverHeight)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[18].offset) =
          value;
      break;
    case 19:
      *reinterpret_cast<decltype(metrics.homeCoverTileHeight)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                kFields[19].offset) = value;
      break;
    case 20:
      *reinterpret_cast<decltype(metrics.homeRecentBooksCount)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                 kFields[20].offset) = value;
      break;
    case 21:
      *reinterpret_cast<decltype(metrics.homeContinueReadingInMenu)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                      kFields[21].offset) = value != 0;
      break;
    case 22:
      *reinterpret_cast<decltype(metrics.homeMenuTopOffset)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                              kFields[22].offset) = value;
      break;
    case 23:
      *reinterpret_cast<decltype(metrics.buttonHintsHeight)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                              kFields[23].offset) = value;
      break;
    case 24:
      *reinterpret_cast<decltype(metrics.sideButtonHintsWidth)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                 kFields[24].offset) = value;
      break;
    case 25:
      *reinterpret_cast<decltype(metrics.progressBarHeight)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                              kFields[25].offset) = value;
      break;
    case 26:
      *reinterpret_cast<decltype(metrics.progressBarMarginTop)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                 kFields[26].offset) = value;
      break;
    case 27:
      *reinterpret_cast<decltype(metrics.statusBarHorizontalMargin)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                      kFields[27].offset) = value;
      break;
    case 28:
      *reinterpret_cast<decltype(metrics.statusBarVerticalMargin)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                    kFields[28].offset) = value;
      break;
    case 29:
      *reinterpret_cast<decltype(metrics.keyboardKeyWidth)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                             kFields[29].offset) = value;
      break;
    case 30:
      *reinterpret_cast<decltype(metrics.keyboardKeyHeight)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                              kFields[30].offset) = value;
      break;
    case 31:
      *reinterpret_cast<decltype(metrics.keyboardKeySpacing)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                               kFields[31].offset) = value;
      break;
    case 32:
      *reinterpret_cast<decltype(metrics.keyboardBottomKeyHeight)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                    kFields[32].offset) = value;
      break;
    case 33:
      *reinterpret_cast<decltype(metrics.keyboardBottomKeySpacing)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                     kFields[33].offset) = value;
      break;
    case 34:
      *reinterpret_cast<decltype(metrics.keyboardBottomAligned)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                  kFields[34].offset) = value != 0;
      break;
    case 35:
      *reinterpret_cast<decltype(metrics.keyboardCenteredText)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                 kFields[35].offset) = value != 0;
      break;
    case 36:
      *reinterpret_cast<decltype(metrics.keyboardVerticalOffset)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                   kFields[36].offset) = value;
      break;
    case 37:
      *reinterpret_cast<decltype(metrics.keyboardTextFieldWidthPercent)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                          kFields[37].offset) = value;
      break;
    case 38:
      *reinterpret_cast<decltype(metrics.keyboardWidthPercent)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                 kFields[38].offset) = value;
      break;
    case 39:
      *reinterpret_cast<decltype(metrics.keyboardKeyCornerRadius)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                    kFields[39].offset) = value;
      break;
    case 40:
      *reinterpret_cast<decltype(metrics.keyboardFillUnselected)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                   kFields[40].offset) = value != 0;
      break;
    case 41:
      *reinterpret_cast<decltype(metrics.keyboardOutlineAllUnselected)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                         kFields[41].offset) = value != 0;
      break;
    case 42:
      *reinterpret_cast<decltype(metrics.keyboardDrawSpecialOutlineWhenUnselected)*>(
          reinterpret_cast<uint8_t*>(&metrics) + kFields[42].offset) = value != 0;
      break;
    case 43:
      *reinterpret_cast<decltype(metrics.keyboardSecondaryLabelRightPadding)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                               kFields[43].offset) = value;
      break;
    case 44:
      *reinterpret_cast<decltype(metrics.keyboardSecondaryLabelTopPadding)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                             kFields[44].offset) = value;
      break;
    case 45:
      *reinterpret_cast<decltype(metrics.keyboardMinArrowHeadSize)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                     kFields[45].offset) = value;
      break;
    case 46:
      *reinterpret_cast<decltype(metrics.popupTopOffsetRatio)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                kFields[46].offset) =
          __builtin_bit_cast(float, static_cast<uint32_t>(value));
      break;
    case 47:
      *reinterpret_cast<decltype(metrics.popupMarginX)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[47].offset) =
          value;
      break;
    case 48:
      *reinterpret_cast<decltype(metrics.popupMarginY)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[48].offset) =
          value;
      break;
    case 49:
      *reinterpret_cast<decltype(metrics.popupFrameThickness)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                kFields[49].offset) = value;
      break;
    case 50:
      *reinterpret_cast<decltype(metrics.popupCornerRadius)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                              kFields[50].offset) = value;
      break;
    case 51:
      *reinterpret_cast<decltype(metrics.popupTextBold)*>(reinterpret_cast<uint8_t*>(&metrics) + kFields[51].offset) =
          value != 0;
      break;
    case 52:
      *reinterpret_cast<decltype(metrics.popupTextInverted)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                              kFields[52].offset) = value != 0;
      break;
    case 53:
      *reinterpret_cast<decltype(metrics.popupTextBaselineOffsetY)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                     kFields[53].offset) = value;
      break;
    case 54:
      *reinterpret_cast<decltype(metrics.popupProgressBarHeight)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                   kFields[54].offset) = value;
      break;
    case 55:
      *reinterpret_cast<decltype(metrics.popupProgressDrawOutline)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                     kFields[55].offset) = value != 0;
      break;
    case 56:
      *reinterpret_cast<decltype(metrics.popupProgressClampPercent)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                      kFields[56].offset) = value != 0;
      break;
    case 57:
      *reinterpret_cast<decltype(metrics.popupProgressFillInverted)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                      kFields[57].offset) = value != 0;
      break;
    case 58:
      *reinterpret_cast<decltype(metrics.popupProgressOutlineInverted)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                         kFields[58].offset) = value != 0;
      break;
    case 59:
      *reinterpret_cast<decltype(metrics.textFieldHorizontalPadding)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                       kFields[59].offset) = value;
      break;
    case 60:
      *reinterpret_cast<decltype(metrics.textFieldNormalThickness)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                     kFields[60].offset) = value;
      break;
    case 61:
      *reinterpret_cast<decltype(metrics.textFieldCursorThickness)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                     kFields[61].offset) = value;
      break;
    case 62:
      *reinterpret_cast<decltype(metrics.textFieldLineEndOffset)*>(reinterpret_cast<uint8_t*>(&metrics) +
                                                                   kFields[62].offset) = value;
      break;
  }
}

}  // namespace PocketDaily::LiveStudio::ThemeField
