#!/usr/bin/env python3
"""Generate the stable ThemeMetrics field-id registry for .uipack files.

Parses `struct ThemeMetrics` from src/components/themes/BaseTheme.h and emits:
  - src/pocket_daily/live_studio/ThemeFieldIds.h (C++ header, id enum + apply switch)
  - scripts/theme_fields.json (same registry for pack builders)

Field ids are declaration order and MUST stay stable once shipped: packs
carry ids, the loader validates against the whitelist. Re-run this script
only when ThemeMetrics gains fields (new ids append; never reorder).
"""

import json
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
THEME_H = REPO / "src/components/themes/BaseTheme.h"
OUT_H = REPO / "src/pocket_daily/live_studio/ThemeFieldIds.h"
OUT_JSON = REPO / "scripts/theme_fields.json"

TYPE_CODES = {"int": 1, "bool": 2, "float": 3}


def parse_metrics(path: Path):
    text = path.read_text()
    match = re.search(r"struct ThemeMetrics \{(.*?)\};", text, re.S)
    if not match:
        sys.exit("ThemeMetrics not found")
    fields = []
    for line in match.group(1).splitlines():
        line = line.strip()
        m = re.match(r"^(int|bool|float)\s+([A-Za-z_][A-Za-z0-9_]*);$", line)
        if m:
            fields.append({"name": m.group(2), "type": TYPE_CODES[m.group(1)]})
    return fields


def emit_header(fields):
    guard = fields[0]["name"]
    lines = [
        "#pragma once",
        "// Generated by scripts/gen_theme_fields.py from BaseTheme.h - DO NOT EDIT.",
        "// Stable field-id registry for .uipack theme overrides (docs/live-studio-v1.md).",
        "// Ids are declaration order and must never be reordered or reused.",
        "",
        '#include "components/themes/BaseTheme.h"',
        "",
        "#include <cstdint>",
        "",
        "namespace PocketDaily::LiveStudio::ThemeField {",
        "",
        "enum FieldId : uint16_t {",
    ]
    for i, f in enumerate(fields):
        suffix = "," if i < len(fields) - 1 else ""
        name = f["name"][0].upper() + f["name"][1:]
        lines.append(f"  k{name} = {i}{suffix}")
    lines += [
        "};",
        "",
        f"inline constexpr size_t kFieldCount = {len(fields)};",
        "",
        "// 1=int, 2=bool, 3=float - the .uipack record type codes.",
        "struct FieldDef {",
        "  const char* name;",
        "  uint8_t type;",
        "  uint16_t offset;",
        "};",
        "",
        "inline constexpr FieldDef kFields[kFieldCount] = {",
    ]
    for f in fields:
        lines.append(f'    {{"{f["name"]}", {f["type"]}, __builtin_offsetof(ThemeMetrics, {f["name"]})}},')
    lines += [
        "};",
        "",
        "// Applies one validated override. Unknown ids are ignored by the caller's",
        "// whitelist check; this switch is the single write path.",
        "inline void applyOverride(ThemeMetrics& metrics, uint16_t id, uint8_t type, int32_t value) {",
        "  if (id >= kFieldCount || type != kFields[id].type) return;",
        "  switch (id) {",
    ]
    for i, f in enumerate(fields):
        t = f["type"]
        if t == 1:
            expr = "value"
        elif t == 2:
            expr = "value != 0"
        else:
            expr = "__builtin_bit_cast(float, static_cast<uint32_t>(value))"
        lines.append(f"    case {i}: *reinterpret_cast<decltype(metrics.{f['name']})*>("
                     f"reinterpret_cast<uint8_t*>(&metrics) + kFields[{i}].offset) = {expr}; break;")
    lines += [
        "  }",
        "}",
        "",
        "}  // namespace PocketDaily::LiveStudio::ThemeField",
        "",
    ]
    OUT_H.write_text("\n".join(lines))


def main():
    fields = parse_metrics(THEME_H)
    if not fields:
        sys.exit("no fields parsed")
    emit_header(fields)
    OUT_JSON.write_text(json.dumps({"fields": fields}, indent=2) + "\n")
    print(f"{len(fields)} fields -> {OUT_H.name}, {OUT_JSON.name} (first: {fields[0]['name']}, last: {fields[-1]['name']})")


if __name__ == "__main__":
    main()
