#!/usr/bin/env python3
"""Generate deterministic Pocket Daily font coverage from shipped content."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
CONTENT = ROOT / "learning/content/jp-n3-ko.json"
TRANSLATIONS = ROOT / "lib/I18n/translations"
JP_OUTPUT = ROOT / "assets/fonts/PocketJP/coverage.txt"
WORLD_OUTPUT = ROOT / "assets/fonts/PocketWorld/coverage.txt"

ASCII = r'''ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789 !"#$%&'()*+,-./:;<=>?@[\]^_`{|}~'''
FIELDS = ("glyph", "primaryWord", "wordReading", "meaningEn", "example")


def rendered_lines() -> list[str]:
    document = json.loads(CONTENT.read_text(encoding="utf-8"))
    lines = ["今日の漢字", "（） ·"]
    seen = set(lines)
    for record in document["records"]:
        for field in FIELDS:
            value = str(record[field])
            if value and value not in seen:
                seen.add(value)
                lines.append(value)
    return lines


def translated_ui_lines() -> list[str]:
    """Load every declared UI translation without adding a YAML dependency."""
    characters: set[str] = set()
    for path in sorted(TRANSLATIONS.glob("*.yaml")):
        for raw in path.read_text(encoding="utf-8").splitlines():
            stripped = raw.strip()
            if not stripped or stripped.startswith("#"):
                continue
            _, encoded = stripped.split(":", 1)
            value = json.loads(encoded.strip())
            value = "".join(char for char in value if ord(char) >= 0x20).rstrip()
            characters.update(value)
    # The UI prefix prevents a digit-only coverage line from being interpreted
    # as a numeric codepoint by check-cpfont-coverage.py.
    return ["UI " + "".join(sorted(characters))]


def write(path: Path, title: str, lines: list[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    text = [
        f"# {title}",
        "# Generated by scripts/generate-pocket-font-coverage.py; do not edit.",
        ASCII,
        "U+FFFD",
        *lines,
        "",
    ]
    path.write_text("\n".join(text), encoding="utf-8")


def main() -> int:
    lines = rendered_lines()
    write(JP_OUTPUT, "Pocket Daily cumulative N5-N3 rendered strings", lines)
    write(
        WORLD_OUTPUT,
        "Pocket Daily automatic world-font regression strings",
        lines
        + translated_ui_lines()
        + [
            "포켓 데일리 오늘의 학습 동기화 완료",
            "中文字体自动选择",
            "日本語 한국어 中文 English Ελληνικά Русский Українська עברית",
        ],
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
